[package]
name = "phf_macros"
version = "0.8.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Macros to generate types in the phf crate"
repository = "https://github.com/sfackler/rust-phf"

[lib]
proc-macro = true

[dependencies]
syn = { version = "0.15", features = ["full"] }
quote = "0.6"
proc-macro2 = "0.4"

phf_generator = { version = "0.8.0", path = "../phf_generator" }
phf_shared = { version = "0.8.0", path = "../phf_shared" }

[dev-dependencies]
compiletest_rs = "=0.3.18"
phf = { version = "0.8.0", path = "../phf", features = ["macros"] }
